### ISSUE TITLE
guess release notes: special-case curl

### ISSUE THREAD

**Issue by dscho** [git-for-windows/gfw-helper-github-app#37]
Just as https://github.com/git-for-windows/gfw-helper-github-app/pull/35 did for OpenSSL, it would be nice if we could link directly to cURL's changelog from our Release Notes instead of the tag (https://github.com/git-for-windows/build-extra/commit/120bab812ffc071b0adb7cb25787fa59e071d7f0 links to https://github.com/curl/curl/releases/tag/curl-8_2_0 but https://curl.se/changes.html#8_2_0 is probably a better link for anybody interested in the details).

**Comment by rimrul** [comment]
We do already special case `curl` (#34). And that work if we add the release note from the issue ([8.1.2](https://github.com/git-for-windows/build-extra/blob/8586164d5ed7ec7eb227e5f5a7d97c47b49657e3/ReleaseNotes.md?plain=1#L265), [8.2.1](https://github.com/git-for-windows/build-extra/blob/8586164d5ed7ec7eb227e5f5a7d97c47b49657e3/ReleaseNotes.md?plain=1#L210),  [8.7.1](https://github.com/git-for-windows/build-extra/blob/8586164d5ed7ec7eb227e5f5a7d97c47b49657e3/ReleaseNotes.md?plain=1#L133)) or the `MSYS2-packages` PR ([8.6.0](https://github.com/git-for-windows/build-extra/blob/8586164d5ed7ec7eb227e5f5a7d97c47b49657e3/ReleaseNotes.md?plain=1#L161)), but not from the `MINGW-packages` PR ([8.4.0](https://github.com/git-for-windows/build-extra/blob/8586164d5ed7ec7eb227e5f5a7d97c47b49657e3/ReleaseNotes.md?plain=1#L180),  [8.8.0](https://github.com/git-for-windows/build-extra/blob/8586164d5ed7ec7eb227e5f5a7d97c47b49657e3/ReleaseNotes.md?plain=1#L71)),
